### ISSUE TITLE
Can't pickle local object 'compute_hs.<locals>.initializer' 

### ISSUE THREAD

**Issue by diegoalexespi** [YosefLab/Hotspot#9]
Hello,

Thank you for the interesting package. 

I am running into an issue when attempting to set the `jobs` parameter in `compute_autocorrelations` and `compute_local_correlations` to anything greater than 1

 In the tutorial at https://yoseflab.github.io/Hotspot/CD4_Tutorial.html, if I set `jobs = 1` in code block 6  (e.g. `hs_results = hs.compute_autocorrelations(jobs=1)`), the code completes without warning/error. If I set `jobs` to an integer greater than 1, I receive the following error: `Can't pickle local object 'compute_hs.<locals>.initializer'`. I receive a similar error in `compute_local_correlations` (`Can't pickle local object 'compute_hs_pairs_centered_cond.<locals>.initializer'`)

I am using hotspot version 0.9.1, numpy version 1.19.1, scipy version 1.5.2, sklearn version 0.23.2, & pandas version 1.2.4.

Happy to share more info if needed. Thanks!

**Comment by deto** [comment]
Hi Diego - I suspect it must be some combination of versions affecting things.  To get some more info - what version of Python are you running it on, and what operating system?

**Comment by diegoalexespi** [comment]
So, I'm using Python 3.8.3 on Mac OS. However, I found that by downgrading my `pandas` version to 0.25.1 like the version that was utilized in the Hotspot manuscript repository (https://github.com/deto/Hotspot_Analysis) I was able to get around the issue, no errors now!

**Comment by deto** [comment]
Ok, glad you are unstuck.  I'll have to look into this further to figure out why the newer Pandas is having an issue.  Sounds like maybe they changed the underlying structure of something to where it can't be pickled now (multiprocessing uses pickling to send things between subprocesses).

**Comment by PSSUN** [comment]
Hi, I met the same problem:

**when running:**
`local_correlations = hs.compute_local_correlations(hs_genes, jobs=4) # jobs for parallelization`

**The error is:**
> Computing pair-wise local correlation on 7580 features...
100%|██████████| 7580/7580 [00:00<00:00, 10181.37it/s]
Traceback (most recent call last):
  File "F:\conda\envs\spatial\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-39b428caec04>", line 3, in <module>
    local_correlations = hs.compute_local_correlations(hs_genes, jobs=4) # jobs for parallelization
  File "F:\conda\envs\spatial\lib\site-packages\hotspot\hotspot.py", line 469, in compute_local_correlations
    lc, lcz = compute_hs_pairs_centered_cond(
  File "F:\conda\envs\spatial\lib\site-packages\hotspot\local_stats_pairs.py", line 763, in compute_hs_pairs_centered_cond
    with multiprocessing.Pool(
  File "F:\conda\envs\spatial\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "F:\conda\envs\spatial\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "F:\conda\envs\spatial\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "F:\conda\envs\spatial\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "F:\conda\envs\spatial\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "F:\conda\envs\spatial\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "F:\conda\envs\spatial\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\conda\envs\spatial\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'compute_hs_pairs_centered_cond.<locals>.initializer'
F:\software\PyCharm 2023.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_resolver.py:178: DeprecationWarning: Use is_view instead of isview, isview will be removed in the future.
  attr = getattr(var, n)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\conda\envs\spatial\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "F:\conda\envs\spatial\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by PSSUN** [comment]
My python version is:

> Python 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by pcm32** [comment]
This unfortunately still happens on a fresh installation (the original error pointed out at the beginning of the issue). Maybe certain packages could be pinned in the dependencies to certain known to work versions? Thanks!
